services:
  devenv:
    build:
      dockerfile: Dockerfile.debian # playwright ei tue alpinea
    container_name: fs-monorepo
    command: sh -c "npm install && tail -f /dev/null"
    volumes:
      # sisällyttä lähdekoodi kontin luettavaksi
      # erota kuitenkin node_modules omaan volumeen
      - ./:/workspace
      - node_modules:/workspace/node_modules
      # git komentoja varten
      - ~/.gitconfig:/home/node/.gitconfig:ro

    ports:
      - '3001-3003:3001-3003' # ulostuleva palvelinliikenne
      - '127.0.0.1:5173-5175:5173-5175' # vite dev
      - '127.0.0.1:9323:9323' # playwright report
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
