POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksInVzZXJuYW1lIjoiYS10ZXJob0BhLmJjZGUiLCJpYXQiOjE3ODA1NjEwODN9.DM-Vz2vlLZOB5wiC9HIkw_tlwO4TRogBPBl_nd4jLLA

{
  "title": "Using Promises",
  "author": "MDN Web Docs",
  "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises",
  "year": 2026
}