name: Deployment pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'osa11/**'
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - 'osa11/**'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: osa11/fs-pokedex
        run: npm install

      - name: Check style
        working-directory: osa11/fs-pokedex
        run: npm run eslint

      - name: Run tests
        working-directory: osa11/fs-pokedex
        run: npm test

      - name: Install Playwright Browsers
        working-directory: osa11/fs-pokedex
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        working-directory: osa11/fs-pokedex
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: osa11/fs-pokedex/playwright-report/
          retention-days: 30

      - name: Build app
        working-directory: osa11/fs-pokedex
        run: npm run build

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  bump_version:
    runs-on: ubuntu-latest
    needs:
      - simple_deployment_pipeline
    steps:
      - uses: actions/checkout@v6

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
