name: Deployment pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'osa11/**'
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - 'osa11/**'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: osa11/fs-pokedex
        run: npm install

      - name: Check style
        working-directory: osa11/fs-pokedex
        run: npm run eslint

      - name: Run tests
        working-directory: osa11/fs-pokedex
        run: npm test

      - name: Install Playwright Browsers
        working-directory: osa11/fs-pokedex
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        working-directory: osa11/fs-pokedex
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: osa11/fs-pokedex/playwright-report/
          retention-days: 30

      - name: Build app
        working-directory: osa11/fs-pokedex
        run: npm run build


  deploy_app:
    # toimii main branch push ja merge commit to main-tilanteissa
    # etsii #skip tagia vain viimeisimmän commitin (head_commit) viestistä
    if: ${{ github.event_name == 'push' && !(github.event.head_commit && contains(github.event.head_commit.message, '#skip')) }}

    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Trigger deployment in Render
        run: curl --fail --silent --show-error ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          # DRY_RUN: true


  announce_deployment:
    runs-on: ubuntu-latest
    needs: [deploy_app]

    steps:
      - name: Announce deployment on Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: "✅ Deployment successful!"
          title: "New version of `fs-pokedex` is ready!"
          description: |
            **Gotta catch 'em all!**

            [View repository](https://github.com/a-terho/fs-exercises/tree/main/osa11)  
            [View commit](${{ github.event.head_commit.url }})
          color: 0xf6cf58

  
  announce_build_fail:
    runs-on: ubuntu-latest
    needs: [simple_deployment_pipeline]
    if: ${{ needs.simple_deployment_pipeline.result == 'failure' }}

    steps:
      - name: Announce build failure on Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nocontext: true
          content: "❌ Build failed!"
          title: "Pipeline error occurred before deployment"
          description: |
            **Repository:** ${{ github.repository }}  
            **Branch:** ${{ github.ref_name }}  
            **Author:** ${{ github.actor }}  
            **Workflow:** ${{ github.workflow }}  
            **Job:** simple_deployment_pipeline
            
            [View failed workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})  
            [View commit](${{ github.event.head_commit.url }})
          color: 0xf62c13
